### ISSUE TITLE
Missing host to link to - assigning host in set_webhook command 

### ISSUE THREAD

**Issue by dvodvo** [telegram-bot-rb/telegram-bot#177]
Running `bin/rake telegram:bot:set_webhook RAILS_ENV=development` leads to the error:  
`ArgumentError: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true` 

[Another issue in this repo ](https://github.com/telegram-bot-rb/telegram-bot/issues/13) provides an answer that would work, but in a single tenant environment.  Assuming a multinenant environment
```
general.example.com
tenant_1.example.com
tenant_2.example.com
```
In a sense, there is confusion for if credentials state a server, that *is* a host, yes?:
```
  telegram:
    bot:
      token: "bot_id:bot_token"
      username: 'some_bot'
      server: "https://general.example.com/"
```
Theoretically, with multiple bots
```
    bots:
      # just set the bot token
      chat: TOKEN_1
      # or add username to support commands with mentions (/help@ChatBot)
      auction:
        token: TOKEN_2
        username: ChatBot
        server: "https://general.example.com/"
```
or is the server attribute not handled under a `bots` block?

is there a way to add the host to the `bin/rake telegram:bot:set_webhook RAILS_ENV=development` command manually, given the multi-domain serving context? 

If not, I am willing to go the curl route as per the documentation API  
`curl -F "url=https://general.example.com/" https://api.telegram.org/bot#{bot_id}:#{bot_token}/setWebhook`  
However this was attempted and the bot is not hitting the application.  Is this is because each action needs to be set individually?

How should it be cast then?
