### ISSUE TITLE
Error when running poller in production 

### ISSUE THREAD

**Issue by douglascamata** [telegram-bot-rb/telegram-bot#3]
```
RAILS_ENV=production bundle exec rake telegram:bot:poller
rake aborted!
Poller not found for :default
/usr/local/opt/rbenv/versions/2.3.0/gemsets/mastermind/gems/telegram-bot-0.6.0/lib/telegram/bot/updates_poller.rb:21:in `start'
/usr/local/opt/rbenv/versions/2.3.0/gemsets/mastermind/gems/telegram-bot-0.6.0/lib/tasks/telegram-bot.rake:7:in `block (3 levels) in <top (required)>'
/usr/local/opt/rbenv/versions/2.3.0/bin/bundle:23:in `load'
/usr/local/opt/rbenv/versions/2.3.0/bin/bundle:23:in `<main>'
Tasks: TOP => telegram:bot:poller
(See full trace by running task with --trace)
```

When running in the development environment everything works fine.

Secrets are as follows:

```
development:
  secret_key_base: d873a75e86e73cb5f0f18961b08d2ea721fe676b050e35caeee3c1e8afb96f62a76f7c8f041417f4f26dc1895831c8dc492589a5f599d14155ae8cf8a33b2e2b
  telegram:
    bot:
      token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
      username: bot_name

test:
  telegram:
    bot:
      token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
      username: bot_name
  secret_key_base: cd7f42ca1d03372280e76cd0e073970bd3522f5986f6a2eccba26782ac66ffcd30655abea290aba9291ec8b75b690b1d3ccfe1451942367453e9d4e867e58466

production:
  telegram:
    bot:
      token: <%= ENV["TELEGRAM_BOT_TOKEN"] %>
      username: bot_name
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
```
